[package]
name = "ascii_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lyon_geom = "1.0.4"
ncurses = "5.101.0"
rand = "0.8.5"
rdev = "0.5.2"
